#!/bin/bash

set -e

print_bundle_part() {
    awk -v "req_part=$1" 'BEGIN { c = 0; } /BEGIN CERT/{c++} c == req_part { print }'
}

cert_is_valid() {
    (openssl x509 -in "$1" -noout -subject || true) | grep -q "Production"
}

maybe_remove_service() {
    if [ -e "/usr/lib/systemd/system/$1" ]; then
	echo "Stopping old $1 service and remove it"
	systemctl stop "$1"
	systemctl disable "$1"
	rm -f "/usr/lib/systemd/system/$1"
    fi
}

# arguments: filename, old path, new path
maybe_move_config() {
    if [ -e "$2/$1" ]; then
	echo "Moving old $1 to new location"
	mv "$2/$1" "$3/$1"
    fi
}

ORIGINAL_CERT=/etc/ssl/certs/device_bundle.crt.pem
TARGET_CERT=/var/lib/wb-cloud-agent/device_bundle.crt.pem
OLD_ETC_PATH=/mnt/data/etc
NEW_ETC_PATH=/mnt/data/etc/wb-cloud-agent/providers/default
OLD_LIB_PATH=/var/lib/wb-cloud-agent
NEW_LIB_PATH=/var/lib/wb-cloud-agent/providers/default
AGENT_CONFIG="${NEW_ETC_PATH}/wb-cloud-agent.conf"

if [ ! -f "$ORIGINAL_CERT" ]; then
    echo "Can't find device certificate!"
    exit 1
fi

mkdir -p "$NEW_LIB_PATH"
mkdir -p "$NEW_ETC_PATH"

# create correct certificate for agent to use
if [ ! -f "$TARGET_CERT" ] || ! cert_is_valid "$TARGET_CERT"; then
    if cert_is_valid "$ORIGINAL_CERT"; then
        echo "Device cert is OK, reusing it"
        rm -f "$TARGET_CERT"
        ln -s "$ORIGINAL_CERT" "$TARGET_CERT"
    else
        echo "Creating fixed bundle certificate"
        print_bundle_part 2 < "$ORIGINAL_CERT" > "$TARGET_CERT"
        print_bundle_part 1 < "$ORIGINAL_CERT" >> "$TARGET_CERT"
    fi
fi

# remove stall activation link file if updated from <=1.2.6
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt "1.2.7~~"; then
    if [ -e "/var/lib/wb-cloud-agent/telegraf.conf" ] && [ -e "/var/lib/wb-cloud-agent/activation_link.conf" ]; then
        echo "Controller seems to be in the cloud already, removing stall activation link"
        echo "unknown" > "/var/lib/wb-cloud-agent/activation_link.conf"
    fi
fi

# migrate from single-tenancy to multi-tenancy
maybe_remove_service wb-cloud-agent.service
maybe_remove_service wb-cloud-agent-frpc.service
maybe_remove_service wb-cloud-agent-telegraf.service
maybe_move_config wb-cloud-agent.conf "$OLD_ETC_PATH" "$NEW_ETC_PATH"
maybe_move_config telegraf.conf "$OLD_LIB_PATH" "$NEW_LIB_PATH"
maybe_move_config frpc.conf "$OLD_LIB_PATH" "$NEW_LIB_PATH"
maybe_move_config activation_link.conf "$OLD_LIB_PATH" "$NEW_LIB_PATH"

# fix agent config (ATECC path according to device version)
. /usr/lib/wb-utils/wb_env.sh
wb_source of

if of_machine_match "wirenboard,wirenboard-720"; then
    sed -i 's/ATECCx08:00:../ATECCx08:00:02/g' "$AGENT_CONFIG"
elif of_machine_match "contactless,imx6ul-wirenboard60"; then
    sed -i 's/ATECCx08:00:../ATECCx08:00:04/g' "$AGENT_CONFIG"
fi

systemctl enable wb-cloud-agent@default.service
systemctl start wb-cloud-agent@default.service

#DEBHELPER#
