#!/bin/bash

set -e

# remove stall activation link file if updated from <=1.2.6
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt "1.2.7~~"; then
    if [ -e "/var/lib/wb-cloud-agent/telegraf.conf" ] && [ -e "/var/lib/wb-cloud-agent/activation_link.conf" ]; then
        echo "Controller seems to be in the cloud already, removing stall activation link"
        echo "unknown" > "/var/lib/wb-cloud-agent/activation_link.conf"
    fi
fi

# Add a provider only if this is the first installation of the package
# or if it is an update from version < 1.6.0
if [ "$1" = "configure" ]; then
    if [ -z "$2" ] || dpkg --compare-versions "$2" lt "1.6.0"; then

        echo "Cleaning up deprecated wb-cloud-agent service and files"
        systemctl stop wb-cloud-agent 2>/dev/null || true
        systemctl disable wb-cloud-agent 2>/dev/null || true
        systemctl stop wb-cloud-agent-telegraf 2>/dev/null || true
        systemctl disable wb-cloud-agent-telegraf 2>/dev/null || true
        systemctl stop wb-cloud-agent.wb-cloud-agent-frpc 2>/dev/null || true
        systemctl disable wb-cloud-agent.wb-cloud-agent-frpc 2>/dev/null || true

        # Delete deprecated files if exists
        rm -f /var/lib/wb-cloud-agent/telegraf.conf
        rm -f /var/lib/wb-cloud-agent/frpc.conf
        rm -f /var/lib/wb-cloud-agent/activation_link.conf

        echo "Add default wirenboard.cloud provider"
        wb-cloud-agent add-provider https://wirenboard.cloud || true
    fi
fi

if [[ -e "/usr/sbin/policy-rc.d" ]] && [[ "$(cat /usr/sbin/policy-rc.d)" == "exit 101" ]]; then
    echo "rootfs building mode, append +update-from-cloud to firmware-compatible"
    grep -qF "+update-from-cloud " /var/lib/wb-image-update/firmware-compatible || echo -n "+update-from-cloud " >> /var/lib/wb-image-update/firmware-compatible
fi

#DEBHELPER#
