# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to ~/.config/fish/completions/wb-cloud-agent.fish
# 2) Ensure a binary named wb-cloud-agent is in your PATH
# See also: https://fishshell.com/docs/current/completions.html#where-to-put-completions


# Parse current commandline:
# - _shtab_wb_cmdpath=(sub)command path seen so far
# - _shtab_wb_npos=number of positional arguments given after it
# - options are skipped based on _shtab_wb_opts_with_value & _shtab_wb_commands lists
function _shtab_wb_scan
  set -g _shtab_wb_cmdpath ''
  set -g _shtab_wb_npos 0
  set -l tokens (commandline -opc)
  set -e tokens[1]
  set -l expect_value 0
  for t in $tokens
    if test $expect_value -eq 1
      set expect_value 0
      continue
    end
    switch "$t"
      case '--*=*'
        continue
      case '-*'
        if contains -- $t $_shtab_wb_opts_with_value
          set expect_value 1
        end
        continue
      case '*'
        if test $_shtab_wb_npos -eq 0
          set -l candidate $t
          if test -n "$_shtab_wb_cmdpath"
            set candidate "$_shtab_wb_cmdpath $t"
          end
          if contains -- $candidate $_shtab_wb_commands
            set -g _shtab_wb_cmdpath $candidate
            continue
          end
        end
        set -g _shtab_wb_npos (math $_shtab_wb_npos + 1)
    end
  end
end

# Condition helper: true if the current (sub)command path equals the given one.
function _shtab_wb_using
  _shtab_wb_scan
  test "$_shtab_wb_cmdpath" = "$argv"
end

set -g _shtab_wb_commands add-provider use-on-premise del-provider del-all-providers cloud-unbind run-daemon
set -g _shtab_wb_opts_with_value --broker --name

complete -c wb-cloud-agent -e
complete -c wb-cloud-agent -f

complete -c wb-cloud-agent -n _shtab_wb_using -s h -l help -d 'show this help message and exit'
complete -c wb-cloud-agent -n '_shtab_wb_using; and test $_shtab_wb_npos -eq 0' -a add-provider -d 'Add new cloud service provider'
complete -c wb-cloud-agent -n '_shtab_wb_using add-provider' -s h -l help -d 'show this help message and exit'
complete -c wb-cloud-agent -n '_shtab_wb_using add-provider' -l name -x -d 'Cloud Provider name to add (override url hostname)'
complete -c wb-cloud-agent -n '_shtab_wb_using; and test $_shtab_wb_npos -eq 0' -a use-on-premise -d 'Delete all cloud service providers and then add new cloud service provider'
complete -c wb-cloud-agent -n '_shtab_wb_using use-on-premise' -s h -l help -d 'show this help message and exit'
complete -c wb-cloud-agent -n '_shtab_wb_using use-on-premise' -l name -x -d 'On-Premise Cloud Provider name to add (override url hostname)'
complete -c wb-cloud-agent -n '_shtab_wb_using; and test $_shtab_wb_npos -eq 0' -a del-provider -d 'Delete cloud service provider'
complete -c wb-cloud-agent -n '_shtab_wb_using del-provider' -s h -l help -d 'show this help message and exit'
complete -c wb-cloud-agent -n '_shtab_wb_using; and test $_shtab_wb_npos -eq 0' -a del-all-providers -d 'Delete all cloud service providers'
complete -c wb-cloud-agent -n '_shtab_wb_using del-all-providers' -s h -l help -d 'show this help message and exit'
complete -c wb-cloud-agent -n '_shtab_wb_using; and test $_shtab_wb_npos -eq 0' -a cloud-unbind -d 'Unbind controller from cloud'
complete -c wb-cloud-agent -n '_shtab_wb_using cloud-unbind' -s h -l help -d 'show this help message and exit'
complete -c wb-cloud-agent -n '_shtab_wb_using; and test $_shtab_wb_npos -eq 0' -a run-daemon -d 'Run cloud agent in daemon mode'
complete -c wb-cloud-agent -n '_shtab_wb_using run-daemon' -s h -l help -d 'show this help message and exit'
complete -c wb-cloud-agent -n '_shtab_wb_using run-daemon' -l broker -x -d 'MQTT broker url'

